import { Platform, StyleSheet } from "react-native";
import { colors, spacing } from "../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  errorBanner: {
    position: "absolute",
    top: Platform.OS === "ios" ? 60 : 40,
    left: spacing.md,
    right: spacing.md,
    backgroundColor: colors.error,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 8,
  },
  errorText: { color: colors.white, textAlign: "center" },
  currentLocationDot: {
    width: 20,
    height: 20,
    borderRadius: 14,
    backgroundColor: "#007AFF",
    borderWidth: 2.5,
    borderColor: "white",
  },

  busStopMarker: {
    alignItems: "center",
    justifyContent: "center",
  },
  busStopIcon: {
    fontSize: 22,
  },
  shuttleStopMarker: {
    alignItems: "center",
  },
  shuttleStopPin: {
    backgroundColor: colors.routeTransit,
    borderRadius: 20,
    padding: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: colors.white,
  },
  shuttleStopLabel: {
    marginTop: 4,
    backgroundColor: colors.white,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.gray300,
    alignItems: "center",
    minWidth: 72,
  },
  shuttleStopCampus: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.primaryDark,
  },
  shuttleStopStartEnd: {
    fontSize: 11,
    color: colors.gray500,
    marginTop: 1,
  },
  busPin: {
    alignItems: "center",
  },
  busPinHead: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    padding: 6,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
  },
  busPinTail: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 10,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderTopColor: colors.primary,
  },

  startDot: {
    width: 20,
    height: 20,
    borderRadius: 14,
    backgroundColor: "white",
    borderWidth: 1.5,
    borderColor: "black",
  },
  destinationPinWrapper: {
    width: 28,
    height: 38,
    alignItems: "center",
    justifyContent: "flex-start",
    overflow: "visible",
  },
  destinationPinHead: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.error,
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 3,
  },
  destinationPinInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.white,
  },
  destinationPinTail: {
    width: 0,
    height: 0,
    marginTop: -2,
    borderLeftWidth: 7,
    borderRightWidth: 7,
    borderTopWidth: 12,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderTopColor: colors.error,
  },

  codePill: {
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 6,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  codeText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.white,
  },
  poiPin: {
    alignItems: "center",
  },
  poiPinHead: {
    borderRadius: 12,
    padding: 5,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 3,
  },
  poiPinTail: {
    width: 0,
    height: 0,
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderTopWidth: 8,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
  },
});
