import { StyleSheet } from "react-native";
import {
    colors as defaultColors,
    spacing,
    typography,
    type ThemePalette,
} from "../constants/theme";
const MARKER_SIZE = 28;
export const createStyles = (colors: ThemePalette = defaultColors) =>
  StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    paddingTop: spacing.md,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    backgroundColor: colors.primary,
  },
  titleLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "rgba(255,255,255,0.65)",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.white,
    letterSpacing: 0.2,
  },
  searchPanel: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    backgroundColor: colors.white,
    gap: spacing.xs,
  },
  buildingTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.primaryDark,
    marginBottom: spacing.xs,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderColor: colors.gray300,
    borderRadius: 10,
    backgroundColor: colors.offWhite,
    paddingHorizontal: spacing.md,
    color: colors.gray700,
  },
  searchButton: {
    minWidth: 84,
    height: 44,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  searchButtonText: {
    color: colors.white,
    fontWeight: typography.button.fontWeight,
    fontSize: typography.body.fontSize,
  },
  suggestionList: {
    borderWidth: 1,
    borderColor: colors.gray300,
    borderRadius: 12,
    backgroundColor: colors.white,
    overflow: "hidden",
  },
  suggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white,
  },
  suggestionItemBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.gray300,
  },
  suggestionIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.secondaryTransparent,
    marginRight: spacing.sm,
  },
  suggestionTextWrap: {
    flex: 1,
  },
  suggestionText: {
    color: colors.gray700,
    fontWeight: typography.button.fontWeight,
    fontSize: typography.body.fontSize,
  },
  suggestionSubtext: {
    color: colors.gray500,
    fontSize: 12,
    marginTop: 2,
  },
  suggestionBadge: {
    marginLeft: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: colors.offWhite,
    borderWidth: 1,
    borderColor: colors.gray300,
  },
  suggestionBadgeText: {
    color: colors.primaryDark,
    fontSize: 11,
    fontWeight: typography.button.fontWeight,
  },
  suggestionEmptyState: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.gray300,
    backgroundColor: colors.offWhite,
  },
  suggestionEmptyText: {
    color: colors.gray500,
    fontSize: typography.body.fontSize,
  },
  selectedRoomBanner: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 10,
    backgroundColor: colors.secondaryTransparent,
  },
  selectedRoomText: {
    color: colors.primaryDark,
    fontWeight: typography.button.fontWeight,
  },
  errorBanner: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 10,
    backgroundColor: "#fde7e7",
    borderWidth: 1,
    borderColor: colors.error,
  },
  errorText: {
    color: colors.error,
    fontWeight: typography.body.fontWeight,
  },
  floorSelectorWrapper: {
    backgroundColor: colors.white,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.gray300,
  },
  floorSelector: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  floorButton: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 20,
    backgroundColor: colors.offWhite,
    borderWidth: 1,
    borderColor: colors.gray300,
    minWidth: 40,
    alignItems: "center",
  },
  floorButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primaryDark,
  },
  floorButtonText: {
    fontSize: typography.body.fontSize,
    fontWeight: typography.button.fontWeight,
    color: colors.primary,
  },
  floorButtonTextActive: {
    color: colors.white,
  },
  mapContainer: {
    flex: 1,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
  },
  mapViewport: {
    flex: 1,
    position: "relative",
    backgroundColor: "#1e1e1e",
    overflow: "hidden",
    borderRadius: 14,
  },
  floorFrame: {
    position: "absolute",
    overflow: "hidden",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.gray300,
    backgroundColor: colors.white,
  },
  floorMetaCard: {
    position: "absolute",
    left: spacing.md,
    top: spacing.md,
    right: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: colors.gray300,
  },
  floorMetaLabel: {
    color: colors.primaryDark,
    fontWeight: typography.button.fontWeight,
    fontSize: typography.body.fontSize,
    marginBottom: spacing.xs,
  },
  floorMetaText: {
    color: colors.gray700,
    fontSize: typography.body.fontSize,
  },
  roomMarker: {
    position: "absolute",
    width: MARKER_SIZE,
    height: MARKER_SIZE,
    alignItems: "center",
    justifyContent: "center",
  },
  roomMarkerPulse: {
    position: "absolute",
    width: MARKER_SIZE,
    height: MARKER_SIZE,
    borderRadius: MARKER_SIZE / 2,
    backgroundColor: colors.secondaryTransparent,
    borderWidth: 3,
    borderColor: colors.secondaryDark,
  },
  roomMarkerInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  accessibleToggle: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.primary,
    gap: 6,
  },
  accessibleToggleActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  accessibleToggleText: {
    fontSize: 13,
    color: colors.primary,
  },
  accessibleToggleTextActive: {
    color: colors.white,
  },
  titleRow: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  marginBottom: 8,
},
});

export const styles = createStyles();
